import Database from 'better-sqlite3'

const MIGRATION_ID = '003_add_contact_profiles'

const SCHEMA_SQL = `
  -- ============================================================
  -- CONTACT PROFILES — Generated by LLM Map-Reduce pipeline
  -- ============================================================
  CREATE TABLE IF NOT EXISTS contact_profiles (
    id TEXT PRIMARY KEY,
    contact_id TEXT UNIQUE NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
    contact_name TEXT NOT NULL,
    profile_text TEXT NOT NULL,
    message_count INTEGER NOT NULL,
    date_range_start TEXT NOT NULL,
    date_range_end TEXT NOT NULL,
    model_used TEXT DEFAULT 'llm-worker',
    block_count INTEGER NOT NULL,
    processing_time_ms INTEGER NOT NULL,
    created_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now')),
    updated_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now'))
  );

  -- Index to speed up retrieval by contact
  CREATE INDEX IF NOT EXISTS idx_contact_profiles_contact ON contact_profiles(contact_id);

  -- ============================================================
  -- BLOCK SUMMARIES — Intermediate Map-Reduce results
  -- ============================================================
  CREATE TABLE IF NOT EXISTS block_summaries (
    id TEXT PRIMARY KEY,
    contact_id TEXT NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
    block_index INTEGER NOT NULL,
    start_date TEXT NOT NULL,
    end_date TEXT NOT NULL,
    message_count INTEGER NOT NULL,
    summary_text TEXT NOT NULL,
    created_at INTEGER NOT NULL DEFAULT (strftime('%s', 'now')),
    UNIQUE(contact_id, block_index)
  );

  CREATE INDEX IF NOT EXISTS idx_block_summaries_contact ON block_summaries(contact_id);
`

export function runMigration003(db: Database.Database): void {
  // Check if this migration was already applied
  const existing = db.prepare(
    'SELECT id FROM _migrations WHERE id = ?'
  ).get(MIGRATION_ID)

  if (existing) {
    console.log('[DB] Migration 003_add_contact_profiles already applied — skipping')
    return
  }

  console.log('[DB] Running migration 003_add_contact_profiles...')

  db.transaction(() => {
    // Apply schema
    db.exec(SCHEMA_SQL)

    // Mark migration as applied
    db.prepare(
      'INSERT INTO _migrations (id) VALUES (?)'
    ).run(MIGRATION_ID)
  })()

  console.log('[DB] Migration 003_add_contact_profiles complete')
}
