export { ChatImportService } from './ChatImportService'
export { ModelManager } from './ModelManager'
export { MODEL_REGISTRY, MODEL_DOWNLOAD_ORDER } from './modelRegistry'
export type { ModelKey, ModelEntry } from './modelRegistry'
export { EmbeddingService } from './EmbeddingService'
export { detectGpu, type GpuInfo } from './gpu-detection'
export { WorkerProcess } from './WorkerProcess'
export { BrainProcess } from './BrainProcess'
